# Generated by Django 2.1.7 on 2019-03-25 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='Nombre del negocio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('address', models.CharField(default='', max_length=512, verbose_name='Dirección')),
                ('food_type', models.IntegerField(default=0, verbose_name='Tipo de Comida')),
                ('price_from', models.FloatField(blank=True, default=0, verbose_name='Precio desde')),
                ('price_to', models.FloatField(blank=True, default=0, verbose_name='Precio hasta')),
                ('rating', models.FloatField(blank=True, default=0, verbose_name='Calificación')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('contact', models.TextField(blank=True, null=True, verbose_name='Contacto')),
                ('url_blog', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Pagina con más info')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar de comida',
                'verbose_name_plural': 'Lugares de comida',
                'ordering': ['name'],
            },
        ),
    ]
