# Generated by Django 2.1.7 on 2019-04-10 15:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Tipo de comida')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de comida',
                'verbose_name_plural': 'Tipos de comida',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='foodlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitud/latitud'),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.FoodType', verbose_name='Tipo de Comida'),
        ),
    ]
